- name: install and start the nginx
  hosts: web
  become: yes
  tasks:
  - name: install the nginx
    ansible.builtin.dnf:
      name: nginx
      sate: present

  - name: start the nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

