- name: Install & Run the Nginx
  hosts: web
  tasks:
  - name: Install the Nginx
    ansible.builtin.package:
      name: Nginx
      sate: present

  - name: Start the Nginx
    ansible.builtin.service:
      name: Nginx
      state: started
      enabled: yes

