- name: variables
  hosts: local
  connection: local
  vars_prompt:
  - name: COURSE
    prompt: Please enter your course
    private: false
  - name: DURATION
    prompt: please enter the course DURATION
    private: false
  - name: TRAINER
    prompt: Enter your trainer name
  tasks:
    - name: print the prompt variables
      ansible.builtin.debug:
        msg: "Duration is {{ DURATION }},Course is {{ COURSE }},Trainer is {{ TRAINER }}"