- name: Install Packages
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: Install the listed Package
    ansible.builtin.package:
    name: "{{ item }}"
    state: installed
    loop:
  - gcc
  - nginx
  - mysql