- name: install Packages
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install Packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: "gcc", state: "absent" }
    - { name: "nginx", state: "absent" }
    - { name: "git", state: "present" }
    - { name: "tar", state: "present" }
    - { name: "zip", state: "present" }