- name: shell vs command
  hosts: local
  connnection: local
  tasks:
  - name: execute ls command in shell module
    ansible.builtin.shell: ls -ltr > /tmp/output.txt

  - name: execute ls command in command module
    ansible.builtin.command: ls -ltr